# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: inca.fhir.uv.osiris
canonical: https://ig-osiris.cancer.fr/ig/osiris
version: 2.1.0
name: OsirisImplementationGuide
title: FHIR Osiris Implementation Guide
status: draft
publisher:
  name: institutcancer
  url: http://cancer.fr
  email: osiris@institutcancer.fr
contact:
  - name: Aurélien JOBARD
    telecom:
      - system: email
        value: osiris@institutcancer.fr
description: An implementation guide about FHIR-osiris to store interoperable data about oncology, including genomics.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.uv.genomics-reporting: 1.0.0
  # todo : migrate to 1.1.0 (http://build.fhir.org/ig/HL7/genomics-reporting/)
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: trial-implementation

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  ValueSets: valuesets.html
  Table of Contents: toc.html
  Artifacts Summary: artifacts.html
  Requests Example: requests.html
  Downloads: downloads.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
    "OSIRIS Spec ": new-tab https://github.com/siric-osiris/OSIRIS
    "inca website ": new-tab http://cancer.fr/

groups:
  Treatment:
    name: Treatment related profiles
    description: Information about patient treatments
    resources:
      - StructureDefinition/treatment
      - StructureDefinition/onco-adverse-event
      - StructureDefinition/response-evaluation
      - StructureDefinition/onco-surgery
      - StructureDefinition/onco-medication-statement
  Clinical:
    name: Clinical data related profiles
    description: Osiris clinical data
    resources:
      - StructureDefinition/onco-patient
      - StructureDefinition/analysis
      - StructureDefinition/sequencing-analysis
      - StructureDefinition/cause-of-death
      - StructureDefinition/vital-status
      - StructureDefinition/family-cancer-history
      - StructureDefinition/onco-biological-sample
      - StructureDefinition/performance-status
      - StructureDefinition/onco-tnm
      - StructureDefinition/biomarker
      - StructureDefinition/related-pathology
      - StructureDefinition/tumor-pathology-event
  Omics:
    name: Omics related profiles
    description: Osiris omics data
    resources:
      - StructureDefinition/variant-annotation
      - StructureDefinition/snp
      - StructureDefinition/fusion
      - StructureDefinition/expression
      - StructureDefinition/copy-number
      - StructureDefinition/sequencing-device
      - StructureDefinition/data-validation
      - StructureDefinition/annotation-reference
      - StructureDefinition/genome-entity
      - StructureDefinition/molecular-sequence-3-prime
      - StructureDefinition/molecular-sequence-5-prime
  General:
    name: General information profiles
    description: Osiris general information
    resources:
      - StructureDefinition/genetic-consent
      - StructureDefinition/clinical-trial
      - StructureDefinition/clinical-trial-subject
      - StructureDefinition/onco-organization
  Radiomics and Radiotherapy:
    name: Radiomics and radiotherapy related ressources
    description: Osiris radiomics & radiotherapy data
    resources:
      - StructureDefinition/imaging-device
      - StructureDefinition/imaging-pacs
      - StructureDefinition/onco-biological-contrast
      - StructureDefinition/onco-imagingstudy-injection
      - StructureDefinition/imaging-service
      - StructureDefinition/radiomics-criteria
      - StructureDefinition/radiomics-features
      - StructureDefinition/radiomics-Image-filters
      - StructureDefinition/roi-segmentation
      - StructureDefinition/onco-imagingstudy
      - StructureDefinition/radiotherapy-course-summary
      - StructureDefinition/radiotherapy-phase
      - StructureDefinition/radiotherapy-plan
      - StructureDefinition/radiotherapy-volume
