ValueSet: VitalStatus
Title: "Vital Status Value Set"
Description:  "Vital status"
* UMLS#C2584946 "Alive (finding)"
* UMLS#C1546956 "Patient Outcome - Died"
* UMLS#C0439673	"Unknown"

ValueSet: CauseOfDeath
Title: "Cause of death Value Set"
Description:  "Cause of death"
* UMLS#C1707251 "Other cancer"
* UMLS#C3262234 "Other cause"
* UMLS#C0679861	"Complications of treatment"
* UMLS#C0027651	"Neoplasm" 
* UMLS#C0277589	"Death of unknown cause"


ValueSet: AnalysisType
Title: "Analysis Types Value Set"
Description:  "Analysis types"
* OSIRIS#C37-1   "Biology"
* OSIRIS#C37-2   "Imaging"
* OSIRIS#C37-3   "Omic"
* OSIRIS#C37-4   "Pathology"
* UMLS#C0439673   "Unknown"

ValueSet: TechnicalProtocol
Title: "Analysis Technical Protocol"
Description:  "Analysis technical protocol"
* OSIRIS#O6-1	"ChIP-on-Chip"
* OSIRIS#O6-2	"ChIP-seq"
* OSIRIS#O6-3	"DNA microarray"
* OSIRIS#O6-4	"DNA targeted panel sequencing"
* OSIRIS#O6-5	"Exome sequencing"
* OSIRIS#O6-6	"Mass spectrometry"
* OSIRIS#O6-7	"MeDIP-Chip"
* OSIRIS#O6-8	"MeDIP-seq"
* OSIRIS#O6-9   "Methylation microarray"
* OSIRIS#O6-10	"RNA microarray"
* OSIRIS#O6-11	"RNA targeted panel sequencing"
* OSIRIS#O6-12	"RNA-seq"
* OSIRIS#O6-13	"RPPA"
* OSIRIS#O6-14	"Whole genome bisulfite sequencing"
* OSIRIS#O6-15	"Whole genome sequencing"
* OSIRIS#O6-16	"miRNA microarray"